// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_unit_test/test/model/api/contact_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_unit_test/models/contact_model.dart' as _i4;
import 'package:flutter_unit_test/models/food_model.dart' as _i5;
import 'package:flutter_unit_test/services/service_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ServiceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceProvider extends _i1.Mock implements _i2.ServiceProvider {
  MockServiceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ContactModel>> fetchAllContact() =>
      (super.noSuchMethod(Invocation.method(#fetchAllContact, []),
              returnValue:
                  Future<List<_i4.ContactModel>>.value(<_i4.ContactModel>[]))
          as _i3.Future<List<_i4.ContactModel>>);
  @override
  _i3.Future<List<_i5.FoodModel>> fetchAllFood() =>
      (super.noSuchMethod(Invocation.method(#fetchAllFood, []),
              returnValue: Future<List<_i5.FoodModel>>.value(<_i5.FoodModel>[]))
          as _i3.Future<List<_i5.FoodModel>>);
}
