name: flutter_final_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Storage

  firebase_core: 
  firebase_auth: 
  firebase_storage:
  cloud_firestore: ^3.1.14
  
  # State Management

  get:
  get_storage:

  # Miscellaneous

  image_picker:
  carousel_slider: ^4.1.1
  loading_animation_widget: ^1.1.0+5
  material_floating_search_bar: ^0.3.7
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.15

  # Rest Api

  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
